# Generated by Django 4.2.13 on 2024-06-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfeedback',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='bookfeedback',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.bookfeedback'),
        ),
    ]
